main:
  method: 'get'
  path: ~
  controller: App\Controller\HomeController
  action: index

movie:
  method: 'get'
  path: movies/{id}
  controller: App\Controller\HomeController
  action: show
  requirements:
    page: '\d+'
